service: my-project

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-offline-sqs

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev

functions:
  helloWorld:
    handler: src/ui/lambdas/HelloWorld.handler
    events:
      - http:
          path: dev
          method: get

  consumer:
    handler: src/ui/lambdas/Consumer.handler
    events:
      - sqs: arn:aws:sqs:region:XXXXXX:MyFirstQueue